FROM maiquelb/embedded-mas-ros:0.4

RUN sudo apt-get update && sudo apt-get install -y wget && wget https://raw.githubusercontent.com/embedded-mas/embedded_mas_ros_example_package/master/install.sh && chmod +x install.sh 

#ToDo: executar o install.sh automaticamente


#CMD ./install.sh 
#CMD ["/install.sh"]
#CMD . /catkin_wsp/devel/setup.bash
#CMD rosrun embedded_mas_examples sum_array_server.py 
